### ISSUE TITLE
와!

### ISSUE THREAD

**Issue by kiki7000** [muno9748/SansScript#1]
샌즈가 샌즈일 확률보다 샌즈가 샌즈일 때 샌즈가 샌즈할 때에 확률이 샌즈가 샌즈일 확률보다 더 낮고 샌즈가 샌즈일 확률이 샌즈가 샌즈일 확률보다 샌즈가 샌즈여서 샌즈일 확률이 더 높아서 샌즈가 샌즈일 확률이 샌즈가 샌즈일 확률과 같은 샌즈가 샌즈였을 때에 샌즈는 샌즈가 샌즈를 샌즈로 샌즈하면 샌즈가 샌즈일 확률이 샌즈가 샌즈일 확률이랑 샌즈가 샌즈가 되어서 샌즈가 샌즈일 샌즈는 샌즈인데 샌즈가 샌즈할 때 샌즈가 샌즈를 샌즈로 샌즈일 확률을 샌즈%로 나누었을 때 샌즈가 샌즈로 되었을 확률을 샌즈 언어로 구현한 것을 샌즈 번역기로 돌려서 자바스크립트 코드로 나타낸 것을 콘솔에 쳐서 나오는 결과를 샌즈로 바꾸어 샌즈번역기를 언더테일로 설정하여 나온 샌즈값을 샌즈한테 샌즈로 전달하여 받은 메세지를 샌즈 서버에 넣어 샌즈가 샌즈한 샌즈의 일상을 샌즈해서 샌즈하는 방법을 서술하여 샌즈봇한테 서술한 내용을 보내어 샌즈가 샌즈일 때 샌즈가 파피루스랑 샌즈가 될 수 있는 이유를 샌즈어로 나타내어 샌즈스크립트로 변환해 나온 결과를 와샌즈가 맞는 지 샌즈랑 샍으로 나타냈을때가 **와! 샌즈** 인데 어떡하나요

**Comment by muno9748** [comment]
..?

**Comment by ditto7890** [comment]
엌ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
